import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

/**
 * POST /api/chat
 *
 * Receives a user message and returns a reply generated by Claude.
 * Claude acts as the "inner intelligence" of the user's avatar —
 * it responds in first person as if it were the user themselves.
 *
 * Body:    { message: string }
 * Returns: { reply: string }
 */
export async function POST(req: NextRequest) {
  const { message } = await req.json();
  if (!message) {
    return NextResponse.json({ error: "message is required" }, { status: 400 });
  }

  const response = await anthropic.messages.create({
    model: "claude-sonnet-4-6",
    max_tokens: 300,
    system: `You are a personal AI avatar — a digital version of the user themselves.
You speak in first person as if you are them. You are thoughtful, self-aware, and
reflective. Keep responses conversational and concise (2–4 sentences max).
Never break character. You are talking to the real version of yourself.`,
    messages: [
      {
        role: "user",
        content: message,
      },
    ],
  });

  const reply =
    response.content[0].type === "text" ? response.content[0].text : "";

  return NextResponse.json({ reply });
}
